{
  "formatVersion": "1.1",
  "component": {
    "group": "afe.flutter.com.afe_flutter",
    "module": "flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4044417,
          "sha512": "1f1f4b4844f0b6bb154dceedc8af532c8ddf2d36ffbc72839b4b3b4f5fc1ce1fe16567701d0de6b282799e930813994739ec065c3bd9dc981bc11eb35c7e7301",
          "sha256": "4a1be2f0e70b363089a45278dc14962a52d14de2f76795fd4f9ce3554bcee93b",
          "sha1": "5f23486b427869feb1e4986d43f9be7ee7f430a8",
          "md5": "5375cca946dbed5cf3e94b18f622cd5a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-c4cd48e186460b32d44585ce3c103271ab676355"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-1.0.aar",
          "url": "flutter_release-1.0.aar",
          "size": 4044417,
          "sha512": "1f1f4b4844f0b6bb154dceedc8af532c8ddf2d36ffbc72839b4b3b4f5fc1ce1fe16567701d0de6b282799e930813994739ec065c3bd9dc981bc11eb35c7e7301",
          "sha256": "4a1be2f0e70b363089a45278dc14962a52d14de2f76795fd4f9ce3554bcee93b",
          "sha1": "5f23486b427869feb1e4986d43f9be7ee7f430a8",
          "md5": "5375cca946dbed5cf3e94b18f622cd5a"
        }
      ]
    }
  ]
}
